### ISSUE TITLE
Audio Streaming Use Case

### ISSUE THREAD

**Issue by soufi** [zboldyga/deduplicator#1]
Hi,

I have a web application that receives audio flac over websocket. The problem here is that sometimes I receive duplicate chunks (which adds a DJ scratching effect to the audio on the other end - server) I my case this is not ideal since I am using a speech-to-text engine .

Do you think I can use your module in this case ? could you give a little example ? 

Cheers.

**Comment by zboldyga** [comment]
Yes, if you want to do server-side de-duplication this is the ideal use case. I'll whip up a quick example for you.

**Comment by zboldyga** [comment]
I added a drop-in example in the /examples folder, and some instructions on how to use it in the README. Let me know if you have any questions :D

**Comment by soufi** [comment]
Hey ! 

Sorry I couldn't respond ! I've used google's farmhash to resolve the problem. 

I will take a look at your examples and get back to you if I have any question ! 

Thank you very much buddy !
